################################################################################
#  Spring Boot Application Deployment & Service
#  Designed and Developed by: @sak_shetty
#  Description:
#     - Deploys Spring Boot App from DockerHub image: sakit333/webapp_dev:latest
#     - Connects to MySQL service named "mysql-container"
#     - Exposes external access via NodePort 30088
################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
  namespace: sak-shetty
  labels:
    app: springapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql-container 3306; do echo waiting for mysql; sleep 5; done;']
      containers:
        - name: springapp
          image: sakit333/webapp_dev:latest
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-container:3306/myapplication?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: SERVER_PORT
              value: "8088"
---
apiVersion: v1
kind: Service
metadata:
  name: springapp
  namespace: sak-shetty
spec:
  selector:
    app: springapp
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 30088
  type: NodePort
